[project]
# please adapt to package name
name = "ghga_validator"
version = "1.2.0"
description = "GHGA Validator - A Python library and command line utility to validate metadata"
dependencies = [
    "typer >= 0.9.0",
    "pydantic >=2, <3",
    "linkml==1.6.1",
    "linkml-runtime==1.6.0",
    "linkml-validator==0.4.5",
    "setuptools==69.1.1"
]

[project.urls]
# please adapt to package name
Repository = "https://github.com/ghga-de/ghga-validator"

[project.scripts]
# please adapt to package name
ghga_validator = "ghga_validator.__main__:run"
