name: PyPI Publish

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Publish tagged release on PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish package
        uses: ghga-de/gh-action-pypi@v0
        with:
          tag: ${{ github.event.release.tag_name }}
          test_pypi_api_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          pypi_api_token: ${{ secrets.PYPI_API_TOKEN }}
