name: PyPI publish

on: push
  # release:
  #   types: [published]

jobs:

  build-package:
    name: Build Package with Verified Version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Version Tag
        uses: ghga-de/gh-action-pypi/verify-version-tag@v1.0.0
        with:
          tag: "1.2.0"

      - name: Build Python Package
        uses: ghga-de/gh-action-pypi/build-python-package@v1.0.0

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist

  test-package:
    name: Test Freshly Built Package
    needs: build-package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Download dist content
        uses: actions/download-artifact@v4

      - name: Test the test-package action
        uses: ghga-de/gh-action-pypi/test-package@v1.0.0
        with:
          python_version: ${{ matrix.python-version }}

  publish-package:
    name: Publish Package
    needs: test-package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download dist content
        uses: actions/download-artifact@v4

      - name: Test the publish-package action
        uses: ghga-de/gh-action-pypi/publish-package@41f5c28ad747ce695f1aa2fec5a155d4a59b4b9a
        with:
          test_pypi_api_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          pypi_api_token: ${{ secrets.PYPI_API_TOKEN }}
          debug_mode: "true"
